-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

REVOKE ALL ON TABLE public."Subcategories" FROM anon;
REVOKE ALL ON TABLE public."Subcategories" FROM authenticated;
REVOKE ALL ON TABLE public."Subcategories" FROM postgres;
REVOKE ALL ON TABLE public."Subcategories" FROM service_role;
REVOKE ALL ON TABLE public."Subcategories" FROM supabase_admin;
GRANT ALL ON TABLE public."Subcategories" TO anon;

GRANT ALL ON TABLE public."Subcategories" TO postgres;

GRANT ALL ON TABLE public."Subcategories" TO supabase_admin;

GRANT ALL ON TABLE public."Subcategories" TO authenticated;

GRANT ALL ON TABLE public."Subcategories" TO service_role;

REVOKE ALL ON TABLE public."Groups" FROM anon;
REVOKE ALL ON TABLE public."Groups" FROM authenticated;
REVOKE ALL ON TABLE public."Groups" FROM postgres;
REVOKE ALL ON TABLE public."Groups" FROM service_role;
REVOKE ALL ON TABLE public."Groups" FROM supabase_admin;
GRANT ALL ON TABLE public."Groups" TO supabase_admin;

GRANT ALL ON TABLE public."Groups" TO authenticated;

GRANT ALL ON TABLE public."Groups" TO anon;

GRANT ALL ON TABLE public."Groups" TO postgres;

GRANT ALL ON TABLE public."Groups" TO service_role;

REVOKE ALL ON TABLE public."Schools" FROM anon;
REVOKE ALL ON TABLE public."Schools" FROM authenticated;
REVOKE ALL ON TABLE public."Schools" FROM postgres;
REVOKE ALL ON TABLE public."Schools" FROM service_role;
REVOKE ALL ON TABLE public."Schools" FROM supabase_admin;
GRANT ALL ON TABLE public."Schools" TO anon;

GRANT ALL ON TABLE public."Schools" TO postgres;

GRANT ALL ON TABLE public."Schools" TO supabase_admin;

GRANT ALL ON TABLE public."Schools" TO authenticated;

GRANT ALL ON TABLE public."Schools" TO service_role;

REVOKE ALL ON TABLE public."Lobbies" FROM anon;
REVOKE ALL ON TABLE public."Lobbies" FROM authenticated;
REVOKE ALL ON TABLE public."Lobbies" FROM postgres;
REVOKE ALL ON TABLE public."Lobbies" FROM service_role;
REVOKE ALL ON TABLE public."Lobbies" FROM supabase_admin;
GRANT ALL ON TABLE public."Lobbies" TO supabase_admin;

GRANT ALL ON TABLE public."Lobbies" TO authenticated;

GRANT ALL ON TABLE public."Lobbies" TO anon;

GRANT ALL ON TABLE public."Lobbies" TO postgres;

GRANT ALL ON TABLE public."Lobbies" TO service_role;

REVOKE ALL ON TABLE public."Categories" FROM anon;
REVOKE ALL ON TABLE public."Categories" FROM authenticated;
REVOKE ALL ON TABLE public."Categories" FROM postgres;
REVOKE ALL ON TABLE public."Categories" FROM service_role;
REVOKE ALL ON TABLE public."Categories" FROM supabase_admin;
GRANT ALL ON TABLE public."Categories" TO anon;

GRANT ALL ON TABLE public."Categories" TO postgres;

GRANT ALL ON TABLE public."Categories" TO supabase_admin;

GRANT ALL ON TABLE public."Categories" TO authenticated;

GRANT ALL ON TABLE public."Categories" TO service_role;

REVOKE ALL ON TABLE public."Groups_Students" FROM anon;
REVOKE ALL ON TABLE public."Groups_Students" FROM authenticated;
REVOKE ALL ON TABLE public."Groups_Students" FROM postgres;
REVOKE ALL ON TABLE public."Groups_Students" FROM service_role;
REVOKE ALL ON TABLE public."Groups_Students" FROM supabase_admin;
GRANT ALL ON TABLE public."Groups_Students" TO supabase_admin;

GRANT ALL ON TABLE public."Groups_Students" TO authenticated;

GRANT ALL ON TABLE public."Groups_Students" TO anon;

GRANT ALL ON TABLE public."Groups_Students" TO postgres;

GRANT ALL ON TABLE public."Groups_Students" TO service_role;

REVOKE ALL ON TABLE public."Students_Schools" FROM anon;
REVOKE ALL ON TABLE public."Students_Schools" FROM authenticated;
REVOKE ALL ON TABLE public."Students_Schools" FROM postgres;
REVOKE ALL ON TABLE public."Students_Schools" FROM service_role;
REVOKE ALL ON TABLE public."Students_Schools" FROM supabase_admin;
GRANT ALL ON TABLE public."Students_Schools" TO anon;

GRANT ALL ON TABLE public."Students_Schools" TO postgres;

GRANT ALL ON TABLE public."Students_Schools" TO supabase_admin;

GRANT ALL ON TABLE public."Students_Schools" TO authenticated;

GRANT ALL ON TABLE public."Students_Schools" TO service_role;

REVOKE ALL ON TABLE public."Lessons" FROM anon;
REVOKE ALL ON TABLE public."Lessons" FROM authenticated;
REVOKE ALL ON TABLE public."Lessons" FROM postgres;
REVOKE ALL ON TABLE public."Lessons" FROM service_role;
REVOKE ALL ON TABLE public."Lessons" FROM supabase_admin;
GRANT ALL ON TABLE public."Lessons" TO supabase_admin;

GRANT ALL ON TABLE public."Lessons" TO authenticated;

GRANT ALL ON TABLE public."Lessons" TO anon;

GRANT ALL ON TABLE public."Lessons" TO postgres;

GRANT ALL ON TABLE public."Lessons" TO service_role;

REVOKE ALL ON TABLE public."Children" FROM anon;
REVOKE ALL ON TABLE public."Children" FROM authenticated;
REVOKE ALL ON TABLE public."Children" FROM postgres;
REVOKE ALL ON TABLE public."Children" FROM service_role;
REVOKE ALL ON TABLE public."Children" FROM supabase_admin;
GRANT ALL ON TABLE public."Children" TO anon;

GRANT ALL ON TABLE public."Children" TO postgres;

GRANT ALL ON TABLE public."Children" TO supabase_admin;

GRANT ALL ON TABLE public."Children" TO authenticated;

GRANT ALL ON TABLE public."Children" TO service_role;

REVOKE ALL ON TABLE public."Schools_Subcategories" FROM anon;
REVOKE ALL ON TABLE public."Schools_Subcategories" FROM authenticated;
REVOKE ALL ON TABLE public."Schools_Subcategories" FROM postgres;
REVOKE ALL ON TABLE public."Schools_Subcategories" FROM service_role;
REVOKE ALL ON TABLE public."Schools_Subcategories" FROM supabase_admin;
GRANT ALL ON TABLE public."Schools_Subcategories" TO anon;

GRANT ALL ON TABLE public."Schools_Subcategories" TO postgres;

GRANT ALL ON TABLE public."Schools_Subcategories" TO supabase_admin;

GRANT ALL ON TABLE public."Schools_Subcategories" TO authenticated;

GRANT ALL ON TABLE public."Schools_Subcategories" TO service_role;

REVOKE ALL ON TABLE public."Students" FROM anon;
REVOKE ALL ON TABLE public."Students" FROM authenticated;
REVOKE ALL ON TABLE public."Students" FROM postgres;
REVOKE ALL ON TABLE public."Students" FROM service_role;
REVOKE ALL ON TABLE public."Students" FROM supabase_admin;
GRANT ALL ON TABLE public."Students" TO anon;

GRANT ALL ON TABLE public."Students" TO postgres;

GRANT ALL ON TABLE public."Students" TO supabase_admin;

GRANT ALL ON TABLE public."Students" TO authenticated;

GRANT ALL ON TABLE public."Students" TO service_role;

REVOKE ALL ON TABLE public."TestTable" FROM anon;
REVOKE ALL ON TABLE public."TestTable" FROM authenticated;
REVOKE ALL ON TABLE public."TestTable" FROM postgres;
REVOKE ALL ON TABLE public."TestTable" FROM service_role;
REVOKE ALL ON TABLE public."TestTable" FROM supabase_admin;
GRANT ALL ON TABLE public."TestTable" TO anon;

GRANT ALL ON TABLE public."TestTable" TO postgres;

GRANT ALL ON TABLE public."TestTable" TO supabase_admin;

GRANT ALL ON TABLE public."TestTable" TO authenticated;

GRANT ALL ON TABLE public."TestTable" TO service_role;

REVOKE ALL ON TABLE public."Addresses_Groups" FROM anon;
REVOKE ALL ON TABLE public."Addresses_Groups" FROM authenticated;
REVOKE ALL ON TABLE public."Addresses_Groups" FROM postgres;
REVOKE ALL ON TABLE public."Addresses_Groups" FROM service_role;
REVOKE ALL ON TABLE public."Addresses_Groups" FROM supabase_admin;
GRANT ALL ON TABLE public."Addresses_Groups" TO anon;

GRANT ALL ON TABLE public."Addresses_Groups" TO postgres;

GRANT ALL ON TABLE public."Addresses_Groups" TO supabase_admin;

GRANT ALL ON TABLE public."Addresses_Groups" TO authenticated;

GRANT ALL ON TABLE public."Addresses_Groups" TO service_role;

REVOKE ALL ON TABLE public."Addresses_Schools" FROM anon;
REVOKE ALL ON TABLE public."Addresses_Schools" FROM authenticated;
REVOKE ALL ON TABLE public."Addresses_Schools" FROM postgres;
REVOKE ALL ON TABLE public."Addresses_Schools" FROM service_role;
REVOKE ALL ON TABLE public."Addresses_Schools" FROM supabase_admin;
GRANT ALL ON TABLE public."Addresses_Schools" TO anon;

GRANT ALL ON TABLE public."Addresses_Schools" TO postgres;

GRANT ALL ON TABLE public."Addresses_Schools" TO supabase_admin;

GRANT ALL ON TABLE public."Addresses_Schools" TO authenticated;

GRANT ALL ON TABLE public."Addresses_Schools" TO service_role;

REVOKE ALL ON TABLE public."Addresses_Teachers" FROM anon;
REVOKE ALL ON TABLE public."Addresses_Teachers" FROM authenticated;
REVOKE ALL ON TABLE public."Addresses_Teachers" FROM postgres;
REVOKE ALL ON TABLE public."Addresses_Teachers" FROM service_role;
REVOKE ALL ON TABLE public."Addresses_Teachers" FROM supabase_admin;
GRANT ALL ON TABLE public."Addresses_Teachers" TO anon;

GRANT ALL ON TABLE public."Addresses_Teachers" TO postgres;

GRANT ALL ON TABLE public."Addresses_Teachers" TO supabase_admin;

GRANT ALL ON TABLE public."Addresses_Teachers" TO authenticated;

GRANT ALL ON TABLE public."Addresses_Teachers" TO service_role;

REVOKE ALL ON TABLE public."Teachers_Subcategories" FROM anon;
REVOKE ALL ON TABLE public."Teachers_Subcategories" FROM authenticated;
REVOKE ALL ON TABLE public."Teachers_Subcategories" FROM postgres;
REVOKE ALL ON TABLE public."Teachers_Subcategories" FROM service_role;
REVOKE ALL ON TABLE public."Teachers_Subcategories" FROM supabase_admin;
GRANT ALL ON TABLE public."Teachers_Subcategories" TO anon;

GRANT ALL ON TABLE public."Teachers_Subcategories" TO postgres;

GRANT ALL ON TABLE public."Teachers_Subcategories" TO supabase_admin;

GRANT ALL ON TABLE public."Teachers_Subcategories" TO authenticated;

GRANT ALL ON TABLE public."Teachers_Subcategories" TO service_role;

REVOKE ALL ON TABLE public."Addresses_LessonSchedules" FROM anon;
REVOKE ALL ON TABLE public."Addresses_LessonSchedules" FROM authenticated;
REVOKE ALL ON TABLE public."Addresses_LessonSchedules" FROM postgres;
REVOKE ALL ON TABLE public."Addresses_LessonSchedules" FROM service_role;
REVOKE ALL ON TABLE public."Addresses_LessonSchedules" FROM supabase_admin;
GRANT ALL ON TABLE public."Addresses_LessonSchedules" TO anon;

GRANT ALL ON TABLE public."Addresses_LessonSchedules" TO postgres;

GRANT ALL ON TABLE public."Addresses_LessonSchedules" TO supabase_admin;

GRANT ALL ON TABLE public."Addresses_LessonSchedules" TO authenticated;

GRANT ALL ON TABLE public."Addresses_LessonSchedules" TO service_role;

REVOKE ALL ON TABLE public."Teachers_Schools" FROM anon;
REVOKE ALL ON TABLE public."Teachers_Schools" FROM authenticated;
REVOKE ALL ON TABLE public."Teachers_Schools" FROM postgres;
REVOKE ALL ON TABLE public."Teachers_Schools" FROM service_role;
REVOKE ALL ON TABLE public."Teachers_Schools" FROM supabase_admin;
GRANT ALL ON TABLE public."Teachers_Schools" TO anon;

GRANT ALL ON TABLE public."Teachers_Schools" TO postgres;

GRANT ALL ON TABLE public."Teachers_Schools" TO supabase_admin;

GRANT ALL ON TABLE public."Teachers_Schools" TO authenticated;

GRANT ALL ON TABLE public."Teachers_Schools" TO service_role;

REVOKE ALL ON TABLE public."LessonSchedules" FROM anon;
REVOKE ALL ON TABLE public."LessonSchedules" FROM authenticated;
REVOKE ALL ON TABLE public."LessonSchedules" FROM postgres;
REVOKE ALL ON TABLE public."LessonSchedules" FROM service_role;
REVOKE ALL ON TABLE public."LessonSchedules" FROM supabase_admin;
GRANT ALL ON TABLE public."LessonSchedules" TO supabase_admin;

GRANT ALL ON TABLE public."LessonSchedules" TO authenticated;

GRANT ALL ON TABLE public."LessonSchedules" TO anon;

GRANT ALL ON TABLE public."LessonSchedules" TO postgres;

GRANT ALL ON TABLE public."LessonSchedules" TO service_role;

REVOKE ALL ON TABLE public."Addresses" FROM anon;
REVOKE ALL ON TABLE public."Addresses" FROM authenticated;
REVOKE ALL ON TABLE public."Addresses" FROM postgres;
REVOKE ALL ON TABLE public."Addresses" FROM service_role;
REVOKE ALL ON TABLE public."Addresses" FROM supabase_admin;
GRANT ALL ON TABLE public."Addresses" TO anon;

GRANT ALL ON TABLE public."Addresses" TO postgres;

GRANT ALL ON TABLE public."Addresses" TO supabase_admin;

GRANT ALL ON TABLE public."Addresses" TO authenticated;

GRANT ALL ON TABLE public."Addresses" TO service_role;

REVOKE ALL ON TABLE public."Teachers" FROM anon;
REVOKE ALL ON TABLE public."Teachers" FROM authenticated;
REVOKE ALL ON TABLE public."Teachers" FROM postgres;
REVOKE ALL ON TABLE public."Teachers" FROM service_role;
REVOKE ALL ON TABLE public."Teachers" FROM supabase_admin;
GRANT ALL ON TABLE public."Teachers" TO anon;

GRANT ALL ON TABLE public."Teachers" TO postgres;

GRANT ALL ON TABLE public."Teachers" TO supabase_admin;

GRANT ALL ON TABLE public."Teachers" TO authenticated;

GRANT ALL ON TABLE public."Teachers" TO service_role;

REVOKE ALL ON TABLE public."Addresses_LobbySchedules" FROM anon;
REVOKE ALL ON TABLE public."Addresses_LobbySchedules" FROM authenticated;
REVOKE ALL ON TABLE public."Addresses_LobbySchedules" FROM postgres;
REVOKE ALL ON TABLE public."Addresses_LobbySchedules" FROM service_role;
REVOKE ALL ON TABLE public."Addresses_LobbySchedules" FROM supabase_admin;
GRANT ALL ON TABLE public."Addresses_LobbySchedules" TO anon;

GRANT ALL ON TABLE public."Addresses_LobbySchedules" TO postgres;

GRANT ALL ON TABLE public."Addresses_LobbySchedules" TO supabase_admin;

GRANT ALL ON TABLE public."Addresses_LobbySchedules" TO authenticated;

GRANT ALL ON TABLE public."Addresses_LobbySchedules" TO service_role;

REVOKE ALL ON TABLE public."LessonScheduleTimes" FROM authenticated;
REVOKE ALL ON TABLE public."LessonScheduleTimes" FROM postgres;
REVOKE ALL ON TABLE public."LessonScheduleTimes" FROM service_role;
GRANT ALL ON TABLE public."LessonScheduleTimes" TO authenticated;

GRANT ALL ON TABLE public."LessonScheduleTimes" TO postgres;

GRANT ALL ON TABLE public."LessonScheduleTimes" TO service_role;

REVOKE ALL ON TABLE public."LobbyScheduleTimes" FROM authenticated;
REVOKE ALL ON TABLE public."LobbyScheduleTimes" FROM postgres;
REVOKE ALL ON TABLE public."LobbyScheduleTimes" FROM service_role;
GRANT ALL ON TABLE public."LobbyScheduleTimes" TO authenticated;

GRANT ALL ON TABLE public."LobbyScheduleTimes" TO postgres;

GRANT ALL ON TABLE public."LobbyScheduleTimes" TO service_role;

REVOKE ALL ON TABLE public."LobbySchedules" FROM anon;
REVOKE ALL ON TABLE public."LobbySchedules" FROM authenticated;
REVOKE ALL ON TABLE public."LobbySchedules" FROM postgres;
REVOKE ALL ON TABLE public."LobbySchedules" FROM service_role;
REVOKE ALL ON TABLE public."LobbySchedules" FROM supabase_admin;
GRANT ALL ON TABLE public."LobbySchedules" TO anon;

GRANT ALL ON TABLE public."LobbySchedules" TO postgres;

GRANT ALL ON TABLE public."LobbySchedules" TO supabase_admin;

GRANT ALL ON TABLE public."LobbySchedules" TO authenticated;

GRANT ALL ON TABLE public."LobbySchedules" TO service_role;
