-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

-- Extension: pg_net

-- DROP EXTENSION pg_net;

CREATE EXTENSION IF NOT EXISTS pg_net
    SCHEMA extensions
    VERSION "0.6";

ALTER TABLE IF EXISTS public."Groups"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Groups" FROM authenticated;
REVOKE ALL ON TABLE public."Groups" FROM anon;
REVOKE ALL ON TABLE public."Groups" FROM service_role;
REVOKE ALL ON TABLE public."Groups" FROM postgres;
GRANT ALL ON TABLE public."Groups" TO authenticated;

GRANT ALL ON TABLE public."Groups" TO anon;

GRANT ALL ON TABLE public."Groups" TO postgres;

GRANT ALL ON TABLE public."Groups" TO service_role;

GRANT ALL ON TABLE public."Groups" TO supabase_admin;

ALTER TABLE IF EXISTS public."Students"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Students" FROM anon;
REVOKE ALL ON TABLE public."Students" FROM authenticated;
REVOKE ALL ON TABLE public."Students" FROM postgres;
REVOKE ALL ON TABLE public."Students" FROM service_role;
GRANT ALL ON TABLE public."Students" TO anon;

GRANT ALL ON TABLE public."Students" TO authenticated;

GRANT ALL ON TABLE public."Students" TO postgres;

GRANT ALL ON TABLE public."Students" TO service_role;

GRANT ALL ON TABLE public."Students" TO supabase_admin;

ALTER TABLE IF EXISTS public."Children"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Children" FROM anon;
REVOKE ALL ON TABLE public."Children" FROM authenticated;
REVOKE ALL ON TABLE public."Children" FROM postgres;
REVOKE ALL ON TABLE public."Children" FROM service_role;
GRANT ALL ON TABLE public."Children" TO anon;

GRANT ALL ON TABLE public."Children" TO authenticated;

GRANT ALL ON TABLE public."Children" TO postgres;

GRANT ALL ON TABLE public."Children" TO service_role;

GRANT ALL ON TABLE public."Children" TO supabase_admin;

ALTER TABLE IF EXISTS public."Addresses_LessonSchedules"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Addresses_LessonSchedules" FROM anon;
REVOKE ALL ON TABLE public."Addresses_LessonSchedules" FROM authenticated;
REVOKE ALL ON TABLE public."Addresses_LessonSchedules" FROM postgres;
REVOKE ALL ON TABLE public."Addresses_LessonSchedules" FROM service_role;
GRANT ALL ON TABLE public."Addresses_LessonSchedules" TO supabase_admin;

GRANT ALL ON TABLE public."Addresses_LessonSchedules" TO authenticated;

GRANT ALL ON TABLE public."Addresses_LessonSchedules" TO anon;

GRANT ALL ON TABLE public."Addresses_LessonSchedules" TO postgres;

GRANT ALL ON TABLE public."Addresses_LessonSchedules" TO service_role;

ALTER TABLE IF EXISTS public."Teachers_Schools"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Teachers_Schools" FROM anon;
REVOKE ALL ON TABLE public."Teachers_Schools" FROM authenticated;
REVOKE ALL ON TABLE public."Teachers_Schools" FROM postgres;
REVOKE ALL ON TABLE public."Teachers_Schools" FROM service_role;
GRANT ALL ON TABLE public."Teachers_Schools" TO anon;

GRANT ALL ON TABLE public."Teachers_Schools" TO authenticated;

GRANT ALL ON TABLE public."Teachers_Schools" TO postgres;

GRANT ALL ON TABLE public."Teachers_Schools" TO service_role;

GRANT ALL ON TABLE public."Teachers_Schools" TO supabase_admin;

ALTER TABLE IF EXISTS public."TestTable"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."TestTable" FROM anon;
REVOKE ALL ON TABLE public."TestTable" FROM authenticated;
REVOKE ALL ON TABLE public."TestTable" FROM postgres;
REVOKE ALL ON TABLE public."TestTable" FROM service_role;
GRANT ALL ON TABLE public."TestTable" TO anon;

GRANT ALL ON TABLE public."TestTable" TO authenticated;

GRANT ALL ON TABLE public."TestTable" TO postgres;

GRANT ALL ON TABLE public."TestTable" TO service_role;

GRANT ALL ON TABLE public."TestTable" TO supabase_admin;

ALTER TABLE IF EXISTS public."Addresses_LobbySchedules"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Addresses_LobbySchedules" FROM anon;
REVOKE ALL ON TABLE public."Addresses_LobbySchedules" FROM authenticated;
REVOKE ALL ON TABLE public."Addresses_LobbySchedules" FROM postgres;
REVOKE ALL ON TABLE public."Addresses_LobbySchedules" FROM service_role;
GRANT ALL ON TABLE public."Addresses_LobbySchedules" TO supabase_admin;

GRANT ALL ON TABLE public."Addresses_LobbySchedules" TO authenticated;

GRANT ALL ON TABLE public."Addresses_LobbySchedules" TO anon;

GRANT ALL ON TABLE public."Addresses_LobbySchedules" TO postgres;

GRANT ALL ON TABLE public."Addresses_LobbySchedules" TO service_role;

ALTER TABLE IF EXISTS public."Addresses_Teachers"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Addresses_Teachers" FROM anon;
REVOKE ALL ON TABLE public."Addresses_Teachers" FROM authenticated;
REVOKE ALL ON TABLE public."Addresses_Teachers" FROM postgres;
REVOKE ALL ON TABLE public."Addresses_Teachers" FROM service_role;
GRANT ALL ON TABLE public."Addresses_Teachers" TO supabase_admin;

GRANT ALL ON TABLE public."Addresses_Teachers" TO authenticated;

GRANT ALL ON TABLE public."Addresses_Teachers" TO anon;

GRANT ALL ON TABLE public."Addresses_Teachers" TO postgres;

GRANT ALL ON TABLE public."Addresses_Teachers" TO service_role;

ALTER TABLE IF EXISTS public."Schools"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Schools" FROM anon;
REVOKE ALL ON TABLE public."Schools" FROM authenticated;
REVOKE ALL ON TABLE public."Schools" FROM postgres;
REVOKE ALL ON TABLE public."Schools" FROM service_role;
GRANT ALL ON TABLE public."Schools" TO anon;

GRANT ALL ON TABLE public."Schools" TO authenticated;

GRANT ALL ON TABLE public."Schools" TO postgres;

GRANT ALL ON TABLE public."Schools" TO service_role;

GRANT ALL ON TABLE public."Schools" TO supabase_admin;

ALTER TABLE IF EXISTS public."Addresses"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Addresses" FROM anon;
REVOKE ALL ON TABLE public."Addresses" FROM authenticated;
REVOKE ALL ON TABLE public."Addresses" FROM postgres;
REVOKE ALL ON TABLE public."Addresses" FROM service_role;
GRANT ALL ON TABLE public."Addresses" TO anon;

GRANT ALL ON TABLE public."Addresses" TO authenticated;

GRANT ALL ON TABLE public."Addresses" TO postgres;

GRANT ALL ON TABLE public."Addresses" TO service_role;

GRANT ALL ON TABLE public."Addresses" TO supabase_admin;

ALTER TABLE IF EXISTS public."Addresses"
    RENAME created_at TO line1;

ALTER TABLE public."Addresses"
    ALTER COLUMN line1 TYPE text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN line1 DROP DEFAULT;

ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN line1 SET STORAGE EXTENDED;

ALTER TABLE IF EXISTS public."Addresses"
    RENAME created_at TO line2;

ALTER TABLE public."Addresses"
    ALTER COLUMN line2 TYPE text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN line2 DROP DEFAULT;

ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN line2 SET STORAGE EXTENDED;

ALTER TABLE IF EXISTS public."Addresses"
    RENAME created_at TO city;

ALTER TABLE public."Addresses"
    ALTER COLUMN city TYPE text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN city DROP DEFAULT;

ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN city SET STORAGE EXTENDED;

ALTER TABLE IF EXISTS public."Addresses"
    RENAME created_at TO "stateCountyProvince";

ALTER TABLE public."Addresses"
    ALTER COLUMN "stateCountyProvince" TYPE text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN "stateCountyProvince" DROP DEFAULT;

ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN "stateCountyProvince" SET STORAGE EXTENDED;

ALTER TABLE IF EXISTS public."Addresses"
    RENAME created_at TO "zipCode";

ALTER TABLE public."Addresses"
    ALTER COLUMN "zipCode" TYPE text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN "zipCode" DROP DEFAULT;

ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN "zipCode" SET STORAGE EXTENDED;

ALTER TABLE IF EXISTS public."Addresses"
    RENAME created_at TO "countryName";

ALTER TABLE public."Addresses"
    ALTER COLUMN "countryName" TYPE text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN "countryName" DROP DEFAULT;

ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN "countryName" SET STORAGE EXTENDED;

ALTER TABLE IF EXISTS public."Addresses"
    RENAME created_at TO "countryCode";

ALTER TABLE public."Addresses"
    ALTER COLUMN "countryCode" TYPE text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN "countryCode" DROP DEFAULT;

ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN "countryCode" SET STORAGE EXTENDED;

ALTER TABLE IF EXISTS public."Addresses"
    RENAME created_at TO "geoPoint";

ALTER TABLE public."Addresses"
    ALTER COLUMN "geoPoint" TYPE text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN "geoPoint" DROP DEFAULT;

ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN "geoPoint" SET STORAGE EXTENDED;

ALTER TABLE IF EXISTS public."Addresses"
    RENAME created_at TO name;

ALTER TABLE public."Addresses"
    ALTER COLUMN name TYPE text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN name DROP DEFAULT;

ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN name SET STORAGE EXTENDED;

ALTER TABLE IF EXISTS public."Addresses"
    RENAME created_at TO id;

ALTER TABLE public."Addresses"
    ALTER COLUMN id TYPE uuid;
ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN id SET DEFAULT uuid_generate_v4();

ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN id SET NOT NULL;

ALTER TABLE IF EXISTS public."Addresses"
    RENAME created_at TO "otherDetails";

ALTER TABLE public."Addresses"
    ALTER COLUMN "otherDetails" TYPE text COLLATE pg_catalog."default";
ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN "otherDetails" DROP DEFAULT;

ALTER TABLE IF EXISTS public."Addresses"
    ALTER COLUMN "otherDetails" SET STORAGE EXTENDED;

ALTER TABLE IF EXISTS public."Addresses_Schools"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Addresses_Schools" FROM anon;
REVOKE ALL ON TABLE public."Addresses_Schools" FROM authenticated;
REVOKE ALL ON TABLE public."Addresses_Schools" FROM postgres;
REVOKE ALL ON TABLE public."Addresses_Schools" FROM service_role;
GRANT ALL ON TABLE public."Addresses_Schools" TO supabase_admin;

GRANT ALL ON TABLE public."Addresses_Schools" TO authenticated;

GRANT ALL ON TABLE public."Addresses_Schools" TO anon;

GRANT ALL ON TABLE public."Addresses_Schools" TO postgres;

GRANT ALL ON TABLE public."Addresses_Schools" TO service_role;

REVOKE ALL ON TABLE public."LessonScheduleTimes" FROM anon;
REVOKE ALL ON TABLE public."LessonScheduleTimes" FROM authenticated;
REVOKE ALL ON TABLE public."LessonScheduleTimes" FROM postgres;
REVOKE ALL ON TABLE public."LessonScheduleTimes" FROM service_role;
GRANT ALL ON TABLE public."LessonScheduleTimes" TO anon;

GRANT ALL ON TABLE public."LessonScheduleTimes" TO authenticated;

GRANT ALL ON TABLE public."LessonScheduleTimes" TO postgres;

GRANT ALL ON TABLE public."LessonScheduleTimes" TO service_role;

ALTER TABLE IF EXISTS public."LessonScheduleTimes"
    RENAME created_at TO "scheduleId";

ALTER TABLE public."LessonScheduleTimes"
    ALTER COLUMN "scheduleId" TYPE uuid;
ALTER TABLE IF EXISTS public."LessonScheduleTimes"
    ALTER COLUMN "scheduleId" SET DEFAULT uuid_generate_v4();

ALTER TABLE IF EXISTS public."LessonScheduleTimes"
    ALTER COLUMN "scheduleId" SET NOT NULL;

ALTER TABLE IF EXISTS public."LessonScheduleTimes"
    RENAME created_at TO "time";

ALTER TABLE public."LessonScheduleTimes"
    ALTER COLUMN time TYPE time without time zone ;
ALTER TABLE IF EXISTS public."LessonScheduleTimes"
    ALTER COLUMN time DROP DEFAULT;

ALTER TABLE IF EXISTS public."LessonScheduleTimes"
    RENAME created_at TO "isBooked";

ALTER TABLE public."LessonScheduleTimes"
    ALTER COLUMN "isBooked" TYPE boolean;
ALTER TABLE IF EXISTS public."LessonScheduleTimes"
    ALTER COLUMN "isBooked" DROP DEFAULT;

ALTER TABLE IF EXISTS public."LessonScheduleTimes"
    RENAME created_at TO id;

ALTER TABLE public."LessonScheduleTimes"
    ALTER COLUMN id TYPE uuid;
ALTER TABLE IF EXISTS public."LessonScheduleTimes"
    ALTER COLUMN id SET DEFAULT uuid_generate_v4();

ALTER TABLE IF EXISTS public."LessonScheduleTimes"
    ALTER COLUMN id SET NOT NULL;

ALTER TABLE IF EXISTS public."Addresses_Groups"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Addresses_Groups" FROM anon;
REVOKE ALL ON TABLE public."Addresses_Groups" FROM authenticated;
REVOKE ALL ON TABLE public."Addresses_Groups" FROM postgres;
REVOKE ALL ON TABLE public."Addresses_Groups" FROM service_role;
GRANT ALL ON TABLE public."Addresses_Groups" TO supabase_admin;

GRANT ALL ON TABLE public."Addresses_Groups" TO authenticated;

GRANT ALL ON TABLE public."Addresses_Groups" TO anon;

GRANT ALL ON TABLE public."Addresses_Groups" TO postgres;

GRANT ALL ON TABLE public."Addresses_Groups" TO service_role;

ALTER TABLE IF EXISTS public."Lobbies"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Lobbies" FROM authenticated;
REVOKE ALL ON TABLE public."Lobbies" FROM anon;
REVOKE ALL ON TABLE public."Lobbies" FROM service_role;
REVOKE ALL ON TABLE public."Lobbies" FROM postgres;
GRANT ALL ON TABLE public."Lobbies" TO authenticated;

GRANT ALL ON TABLE public."Lobbies" TO anon;

GRANT ALL ON TABLE public."Lobbies" TO postgres;

GRANT ALL ON TABLE public."Lobbies" TO service_role;

GRANT ALL ON TABLE public."Lobbies" TO supabase_admin;

ALTER TABLE IF EXISTS public."Categories"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Categories" FROM anon;
REVOKE ALL ON TABLE public."Categories" FROM authenticated;
REVOKE ALL ON TABLE public."Categories" FROM postgres;
REVOKE ALL ON TABLE public."Categories" FROM service_role;
GRANT ALL ON TABLE public."Categories" TO anon;

GRANT ALL ON TABLE public."Categories" TO authenticated;

GRANT ALL ON TABLE public."Categories" TO postgres;

GRANT ALL ON TABLE public."Categories" TO service_role;

GRANT ALL ON TABLE public."Categories" TO supabase_admin;

ALTER TABLE IF EXISTS public."Lessons"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Lessons" FROM authenticated;
REVOKE ALL ON TABLE public."Lessons" FROM anon;
REVOKE ALL ON TABLE public."Lessons" FROM service_role;
REVOKE ALL ON TABLE public."Lessons" FROM postgres;
GRANT ALL ON TABLE public."Lessons" TO authenticated;

GRANT ALL ON TABLE public."Lessons" TO anon;

GRANT ALL ON TABLE public."Lessons" TO postgres;

GRANT ALL ON TABLE public."Lessons" TO service_role;

GRANT ALL ON TABLE public."Lessons" TO supabase_admin;

ALTER TABLE IF EXISTS public."Schools_Subcategories"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Schools_Subcategories" FROM anon;
REVOKE ALL ON TABLE public."Schools_Subcategories" FROM authenticated;
REVOKE ALL ON TABLE public."Schools_Subcategories" FROM postgres;
REVOKE ALL ON TABLE public."Schools_Subcategories" FROM service_role;
GRANT ALL ON TABLE public."Schools_Subcategories" TO supabase_admin;

GRANT ALL ON TABLE public."Schools_Subcategories" TO authenticated;

GRANT ALL ON TABLE public."Schools_Subcategories" TO anon;

GRANT ALL ON TABLE public."Schools_Subcategories" TO postgres;

GRANT ALL ON TABLE public."Schools_Subcategories" TO service_role;

ALTER TABLE IF EXISTS public."Groups_Students"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Groups_Students" FROM authenticated;
REVOKE ALL ON TABLE public."Groups_Students" FROM anon;
REVOKE ALL ON TABLE public."Groups_Students" FROM service_role;
REVOKE ALL ON TABLE public."Groups_Students" FROM postgres;
GRANT ALL ON TABLE public."Groups_Students" TO authenticated;

GRANT ALL ON TABLE public."Groups_Students" TO anon;

GRANT ALL ON TABLE public."Groups_Students" TO postgres;

GRANT ALL ON TABLE public."Groups_Students" TO service_role;

GRANT ALL ON TABLE public."Groups_Students" TO supabase_admin;

ALTER TABLE IF EXISTS public."Subcategories"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Subcategories" FROM anon;
REVOKE ALL ON TABLE public."Subcategories" FROM authenticated;
REVOKE ALL ON TABLE public."Subcategories" FROM postgres;
REVOKE ALL ON TABLE public."Subcategories" FROM service_role;
GRANT ALL ON TABLE public."Subcategories" TO anon;

GRANT ALL ON TABLE public."Subcategories" TO authenticated;

GRANT ALL ON TABLE public."Subcategories" TO postgres;

GRANT ALL ON TABLE public."Subcategories" TO service_role;

GRANT ALL ON TABLE public."Subcategories" TO supabase_admin;

ALTER TABLE IF EXISTS public."Students_Schools"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Students_Schools" FROM anon;
REVOKE ALL ON TABLE public."Students_Schools" FROM authenticated;
REVOKE ALL ON TABLE public."Students_Schools" FROM postgres;
REVOKE ALL ON TABLE public."Students_Schools" FROM service_role;
GRANT ALL ON TABLE public."Students_Schools" TO anon;

GRANT ALL ON TABLE public."Students_Schools" TO authenticated;

GRANT ALL ON TABLE public."Students_Schools" TO postgres;

GRANT ALL ON TABLE public."Students_Schools" TO service_role;

GRANT ALL ON TABLE public."Students_Schools" TO supabase_admin;

ALTER TABLE IF EXISTS public."LessonSchedules"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."LessonSchedules" FROM authenticated;
REVOKE ALL ON TABLE public."LessonSchedules" FROM anon;
REVOKE ALL ON TABLE public."LessonSchedules" FROM service_role;
REVOKE ALL ON TABLE public."LessonSchedules" FROM postgres;
GRANT ALL ON TABLE public."LessonSchedules" TO authenticated;

GRANT ALL ON TABLE public."LessonSchedules" TO anon;

GRANT ALL ON TABLE public."LessonSchedules" TO postgres;

GRANT ALL ON TABLE public."LessonSchedules" TO service_role;

GRANT ALL ON TABLE public."LessonSchedules" TO supabase_admin;

ALTER TABLE IF EXISTS public."Teachers_Subcategories"
    OWNER TO supabase_admin;

COMMENT ON TABLE public."Teachers_Subcategories"
  IS 'Joint table for teachers and subcategories';

REVOKE ALL ON TABLE public."Teachers_Subcategories" FROM anon;
REVOKE ALL ON TABLE public."Teachers_Subcategories" FROM authenticated;
REVOKE ALL ON TABLE public."Teachers_Subcategories" FROM postgres;
REVOKE ALL ON TABLE public."Teachers_Subcategories" FROM service_role;
GRANT ALL ON TABLE public."Teachers_Subcategories" TO supabase_admin;

GRANT ALL ON TABLE public."Teachers_Subcategories" TO authenticated;

GRANT ALL ON TABLE public."Teachers_Subcategories" TO anon;

GRANT ALL ON TABLE public."Teachers_Subcategories" TO postgres;

GRANT ALL ON TABLE public."Teachers_Subcategories" TO service_role;

ALTER TABLE IF EXISTS public."LobbyScheduleTimes"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."LobbyScheduleTimes" FROM anon;
REVOKE ALL ON TABLE public."LobbyScheduleTimes" FROM authenticated;
REVOKE ALL ON TABLE public."LobbyScheduleTimes" FROM postgres;
REVOKE ALL ON TABLE public."LobbyScheduleTimes" FROM service_role;
GRANT ALL ON TABLE public."LobbyScheduleTimes" TO anon;

GRANT ALL ON TABLE public."LobbyScheduleTimes" TO authenticated;

GRANT ALL ON TABLE public."LobbyScheduleTimes" TO postgres;

GRANT ALL ON TABLE public."LobbyScheduleTimes" TO service_role;

GRANT ALL ON TABLE public."LobbyScheduleTimes" TO supabase_admin;

ALTER TABLE IF EXISTS public."LobbyScheduleTimes"
    RENAME created_at TO "time";

ALTER TABLE public."LobbyScheduleTimes"
    ALTER COLUMN time TYPE time without time zone ;
ALTER TABLE IF EXISTS public."LobbyScheduleTimes"
    ALTER COLUMN time DROP DEFAULT;

ALTER TABLE IF EXISTS public."LobbyScheduleTimes"
    RENAME created_at TO "scheduleId";

ALTER TABLE public."LobbyScheduleTimes"
    ALTER COLUMN "scheduleId" TYPE uuid;
ALTER TABLE IF EXISTS public."LobbyScheduleTimes"
    ALTER COLUMN "scheduleId" DROP DEFAULT;

ALTER TABLE IF EXISTS public."LobbyScheduleTimes"
    ALTER COLUMN "scheduleId" SET NOT NULL;

ALTER TABLE IF EXISTS public."LobbyScheduleTimes"
    RENAME created_at TO id;

ALTER TABLE public."LobbyScheduleTimes"
    ALTER COLUMN id TYPE uuid;
ALTER TABLE IF EXISTS public."LobbyScheduleTimes"
    ALTER COLUMN id SET DEFAULT uuid_generate_v4();

ALTER TABLE IF EXISTS public."LobbyScheduleTimes"
    ALTER COLUMN id SET NOT NULL;

ALTER TABLE IF EXISTS public."LobbyScheduleTimes"
    RENAME created_at TO "isBooked";

ALTER TABLE public."LobbyScheduleTimes"
    ALTER COLUMN "isBooked" TYPE boolean;
ALTER TABLE IF EXISTS public."LobbyScheduleTimes"
    ALTER COLUMN "isBooked" DROP DEFAULT;

ALTER TABLE IF EXISTS public."LobbySchedules"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."LobbySchedules" FROM anon;
REVOKE ALL ON TABLE public."LobbySchedules" FROM authenticated;
REVOKE ALL ON TABLE public."LobbySchedules" FROM postgres;
REVOKE ALL ON TABLE public."LobbySchedules" FROM service_role;
GRANT ALL ON TABLE public."LobbySchedules" TO supabase_admin;

GRANT ALL ON TABLE public."LobbySchedules" TO authenticated;

GRANT ALL ON TABLE public."LobbySchedules" TO anon;

GRANT ALL ON TABLE public."LobbySchedules" TO postgres;

GRANT ALL ON TABLE public."LobbySchedules" TO service_role;

ALTER TABLE IF EXISTS public."Teachers"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."Teachers" FROM anon;
REVOKE ALL ON TABLE public."Teachers" FROM authenticated;
REVOKE ALL ON TABLE public."Teachers" FROM postgres;
REVOKE ALL ON TABLE public."Teachers" FROM service_role;
GRANT ALL ON TABLE public."Teachers" TO anon;

GRANT ALL ON TABLE public."Teachers" TO authenticated;

GRANT ALL ON TABLE public."Teachers" TO postgres;

GRANT ALL ON TABLE public."Teachers" TO service_role;

GRANT ALL ON TABLE public."Teachers" TO supabase_admin;
